FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-install-project



COPY frontend/app .
RUN uv sync --locked


ENTRYPOINT ["uv","run","streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]