FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app
COPY pyproject.toml uv.lock ./


RUN uv sync --frozen

COPY backend/app app

CMD ["uv", "run", "fastapi", "run", "app/main.py","--host","0.0.0.0","--port","8000"]







# build first then run it
# docker build -t backend .
# docker run --rm -p 8000:8000 -e OLLAMA_HOST=http://host.docker.internal:11434 -e OLLAMA_MODEL=llama3.1:8b backend