"""
Graph nodes — Data, Experiment, Critic, Judge. Sections below run in that
pipeline order.

    Data Node        deterministic. Inspects the raw CSV, writes a dtype
                     report + edge-case flags to cleaned_data_summary.
    Experiment Node  deterministic wrapper around AutoGluon. A library call,
                     not a decision.
    Critic Node      deterministic, unit-tested. Runs three fixed rule-based
                     tests and writes exactly 3 CriticFinding dicts.
    Judge Agent      the one place an LLM's output changes control flow. The
                     tool-calling agent itself lives in app.agents.tools +
                     app.agents.graph_agent; this module keeps only its
                     deterministic nodes and the two Judge helpers the tools
                     reuse (_rule_based_verdict, _apply_override_guardrail).
    Reporter Node    templated. Renders the finished run into report. No LLM.

Smoke tests live in the __main__ block at the bottom:
    python -m app.agents.nodes [data|experiment|critic|reporter|all]
"""

import builtins
import contextlib
import io
from typing import List, Literal, Optional

import numpy as np
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor
from pydantic import BaseModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from app.artifacts import predictor_path_for_lap
from app.state.agent_state import AgentState


# ---------------------------------------------------------------------------
# Shared schemas
# ---------------------------------------------------------------------------

class CriticFinding(BaseModel):
    test: str                       # "leakage" | "contamination" | "imbalance"
    threshold: float
    measured_value: float
    passed: bool
    detail: str = ""                # human-readable, feeds cited_evidence


# ---------------------------------------------------------------------------
# Dataset loading — the remediation boundary.
#
# Experiment and Critic MUST both read through _load_dataset(). If they diverge
# about what "the data" is, the Critic certifies a dataset the model never
# trained on, and every finding in the report is about the wrong thing.
# ---------------------------------------------------------------------------

# A restricted builtin subset for the REPL cleaning tool. This is a SPEED BUMP,
# not a security sandbox — no import/open/eval/exec, but a determined snippet can
# still escape via object internals. Acceptable because the code is generated by
# our own trusted model against a local dataset, not by an adversary.
_SAFE_BUILTIN_NAMES = [
    "abs", "all", "any", "bool", "dict", "enumerate", "filter", "float", "format",
    "getattr", "hasattr", "int", "isinstance", "len", "list", "map", "max", "min",
    "print", "range", "reversed", "round", "set", "sorted", "str", "sum", "tuple", "zip",
]
SAFE_BUILTINS = {n: getattr(builtins, n) for n in _SAFE_BUILTIN_NAMES}


def _run_cleaning_code(code: str, df: pd.DataFrame) -> tuple[pd.DataFrame, str, Optional[str]]:
    """Execute a cleaning snippet against `df` in a restricted namespace.

    Shared by the live REPL tool (tools.run_cleaning_code) and history replay
    (_apply_remediation), so what the agent sees while iterating is byte-for-byte
    what gets replayed later. Returns (result_df, captured_stdout, error_or_None).

    Restricted, NOT sandboxed (see SAFE_BUILTINS): only df/pd/np and a safe builtin
    subset are exposed — no import/open/eval. `df` is the only persisted output, so
    a snippet must leave its cleaned result in `df`; anything else is inspection.
    """
    ns = {"df": df, "pd": pd, "np": np}
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            exec(code, {"__builtins__": SAFE_BUILTINS}, ns)  # noqa: S102 - restricted, trusted model
    except Exception as e:
        return df, buf.getvalue(), f"{type(e).__name__}: {e}"
    result = ns.get("df")
    if not isinstance(result, pd.DataFrame):
        return df, buf.getvalue(), ("After running, `df` is not a DataFrame — assign "
                                    "your cleaned result back to `df`.")
    return result, buf.getvalue(), None


def _apply_remediation(df: pd.DataFrame, remediation: dict) -> pd.DataFrame:
    """Replay one remediation-history entry against a DataFrame. Deterministic.

    Entries are REPL cleaning steps — {"code": "..."} — re-exec'd via
    _run_cleaning_code (the tool-calling Judge is the only writer of history).
    A stored code step already passed the tool's runtime guard (ran clean, target
    survived), so a replay error here means the data changed underneath us and is
    surfaced loudly rather than silently swallowed.
    """
    if not remediation:
        return df
    if "code" in remediation:
        new_df, _out, err = _run_cleaning_code(remediation["code"], df)
        if err:
            raise RuntimeError(f"Replaying a stored cleaning step failed: {err}")
        return new_df
    return df


def _load_dataset(state: AgentState) -> pd.DataFrame:
    """Read the CSV at dataset_path with EVERY remediation so far applied, in order.

    On lap 1 the history is empty and this is a plain read_csv. On a retry it
    returns the repaired data — the only reason the Critic's findings can differ
    between laps, and so the only reason the loop can end anywhere other than the
    retry bound.

    Replays the whole history rather than a single 'active' directive, because
    repairs must COMPOUND. If lap 1 drops a leaking column and lap 2 prescribes
    a dedupe, applying only lap 2 would hand the model back the leaking column —
    the loop would undo its own fix and oscillate. The Judge is told the findings
    it sees are measured after all prior repairs, so the two must agree.

    The dataset on disk is never mutated: remediation is replayed on every read,
    so dataset_path always refers to exactly what the user uploaded.
    """
    df = pd.read_csv(state["dataset_path"])
    for directive in (state.get("remediation_history") or []):
        df = _apply_remediation(df, directive)
    return df


class JudgeDecision(BaseModel):
    """Full record — LLM fields + code-computed fields.

    Only accept/reject exist: the tool-calling Judge reaches a verdict by calling
    accept_model or reject_run, and iterates via its own tools rather than by
    returning a 'retry' for a Router to loop on.
    """
    verdict: Literal["accept", "reject"]
    selected_model: Optional[str]
    justification: str
    cited_evidence: List[str]
    rule_based_verdict: Literal["accept", "reject"]  # set by code/ its deterministic(not by llm)
    overrode_rules: bool                                       # set by code/(not by llm)
    flagged_for_manual_review: Optional[bool]  =None        # set by code/(not by llm)


# ---------------------------------------------------------------------------
# Data Node — deterministic. No LLM call.
#
# Input:  raw CSV at dataset_path, target_column (post target-column-confirmation UI)
# Output: cleaned_data_summary — dtype report + edge-case flags.
#


def _detect_wrong_dtype_columns(df: pd.DataFrame) -> list[str]:
    """
    Flags object-dtype columns where every non-null value is actually
    numeric (e.g. a column of "1", "2", "3" strings stored as object
    instead of int/float — common CSV-parsing artifact).
    """
    flagged = []
    for col in df.columns:
        if df[col].dtype == "object":
            non_null = df[col].dropna()
            if non_null.empty:
                continue
            numeric_coerced = pd.to_numeric(non_null, errors="coerce")
            if numeric_coerced.notna().all():
                flagged.append(col)
    return flagged


def _detect_empty_columns(df: pd.DataFrame) -> list[str]:
    """Columns that are 100% null."""
    return [col for col in df.columns if df[col].isna().all()]


def _detect_single_class_target(df: pd.DataFrame, target_column: str) -> bool:
    """True if the target column has only one unique non-null value."""
    if target_column not in df.columns:
        return False
    return df[target_column].dropna().nunique() <= 1


def _dtype_report(df: pd.DataFrame) -> dict:
    """Per-column dtype + null count + unique count, for the summary."""
    report = {}
    for col in df.columns:
        report[col] = {
            "dtype": str(df[col].dtype),
            "null_count": int(df[col].isna().sum()),
            "null_fraction": round(float(df[col].isna().mean()), 4),
            "unique_count": int(df[col].nunique(dropna=True)),
        }
    return report


def data_node(state: AgentState) -> AgentState:
    """
    LangGraph node entry point.

    Input (from AgentState):  dataset_path, target_column
    Output (to AgentState):   cleaned_data_summary — dict with:
        n_rows, n_columns, dtype_report, wrong_dtype_columns,
        empty_columns, single_class_target (bool), target_column,
        halt_recommended (bool) — True if single_class_target or the
        target column itself is empty; downstream nodes/Router should
        treat this as a hard stop, not just a warning.
    """
    df = pd.read_csv(state["dataset_path"])
    target_column = state["target_column"]

    wrong_dtype_cols = _detect_wrong_dtype_columns(df)
    empty_cols = _detect_empty_columns(df)
    single_class = _detect_single_class_target(df, target_column)
    target_missing = target_column not in df.columns
    target_is_empty = target_column in empty_cols

    halt_recommended = single_class or target_missing or target_is_empty

    summary = {
        "n_rows": len(df),
        "n_columns": len(df.columns),
        "target_column": target_column,
        "dtype_report": _dtype_report(df),
        "wrong_dtype_columns": wrong_dtype_cols,
        "empty_columns": empty_cols,
        "single_class_target": single_class,
        "target_column_missing": target_missing,
        "halt_recommended": halt_recommended,
    }

    return {"cleaned_data_summary": summary}


# ---------------------------------------------------------------------------
# Experiment Node — deterministic wrapper around AutoGluon. No LLM call.
#
# Fits a TabularPredictor on the dataset, packages the leaderboard into
# AgentState-compatible shape. This is a library call, not a decision —
# all judgment happens downstream in the Critic Node and Judge Agent.

# ---------------------------------------------------------------------------

def experiment_node(state: AgentState) -> AgentState:
    """
    LangGraph node entry point.

    Input (from AgentState):  dataset_path, target_column, remediation, run_id
    Output (to AgentState):   leaderboard — list[dict], ranked best-first,
                               each entry carrying at minimum a 'model' key
                               and a 'score_val' key (Judge/Critic depend on
                               'model' specifically — the Reporter reads
                               leaderboard[0]["model"] directly).
                              predictor_path — where THIS lap's fitted models
                               were written, so the accepted one can be exported
                               and downloaded once the run ends.

    Runs once per lap of the remediation cycle. Reads the data through
    _load_dataset(), so on a retry it refits on the REPAIRED dataset — that
    refit is the point of the lap, and the reason the resulting leaderboard is
    comparable to the Critic's re-measurement of the same frame.

    time_limit and presets are pinned per Day-0 §3 / §4 (sequential
    AutoGluon -> Ollama execution, medium_quality for spike speed).
    Do not relitigate these in isolation — they're a shared VRAM/timing
    decision, not just an Experiment Node choice.
    """
    df = _load_dataset(state)
    target_column = state["target_column"]

    # Pin where AutoGluon writes. Left unset it picks ./AutogluonModels/ag-<ts>/
    # relative to the process cwd and nothing records the path — the models get
    # fit, then orphaned. The lap number comes from leaderboard_history rather
    # than retry_count because refit_and_recritique calls us BEFORE it increments
    # retry_count, so the initial fit and the first refit would collide on lap 0.
    lap = len(state.get("leaderboard_history") or [])
    predictor = TabularPredictor(
        label=target_column,
        verbosity=0,
        path=predictor_path_for_lap(state.get("run_id"), lap),
    ).fit(
        TabularDataset(df),
        time_limit=60,
        presets="medium_quality",
    )

    leaderboard_df = predictor.leaderboard(silent=True)
    leaderboard = leaderboard_df.to_dict(orient="records")

    return {
        "leaderboard": leaderboard,
        # Read back off the predictor, not the path we asked for: AutoGluon
        # normalises it (and invents one when we passed None).
        "predictor_path": str(predictor.path),
        # Current truth for the Judge, AND one appended entry so the Reporter can
        # still quote this lap's score after a later lap overwrites `leaderboard`.
        # Top 3 only — that's all the report renders, and the full frame is heavy.
        "leaderboard_history": [leaderboard[:3]],
        "cleaned_data_summary": {
            **state.get("cleaned_data_summary", {}),
            "problem_type": predictor.problem_type,
            "fit_time_seconds": round(sum(
                row.get("fit_time", 0) for row in leaderboard
            ), 2),
            # Shape AFTER remediation, so a report on lap 2 doesn't quote the
            # raw upload's dimensions for a model that never saw them.
            "n_rows_fitted": len(df),
            "n_columns_fitted": len(df.columns),
        },
    }


# ---------------------------------------------------------------------------
# Critic Node — deterministic, unit-tested. No LLM call.
#
# Runs three fixed rule-based tests against the raw CSV at dataset_path, and
# returns a list of exactly 3 CriticFinding dicts (leakage, contamination,
# imbalance) — matching the CriticFinding schema above and
# app/mocks/critic_findings.py's fixture shape exactly.
#
# Reads NOTHING from the Experiment Node: not the leaderboard, not the fitted
# predictor. All three tests are properties of the dataset alone, so this node
# has no data dependency on Experiment despite running after it in the graph.
# Note the consequence for the imbalance test — see check_imbalance below.
#
# Thresholds (Day-0 §5 / mocks/critic_findings.py — single source of truth,
# do not diverge from these without updating both places):
#     leakage         max |feature-target correlation|   fails when > 0.95
#     contamination   fraction of exact/near-dup rows    fails when > 0.01
#     imbalance       minority-class recall              fails when < 0.50
#
# Owner: Lokav
# ---------------------------------------------------------------------------

LEAKAGE_THRESHOLD = 0.95
CONTAMINATION_THRESHOLD = 0.01
IMBALANCE_THRESHOLD = 0.50


def _finding(test: str, threshold: float, measured_value: float,
             passed: bool, detail: str = "") -> dict:
    """One CriticFinding as a plain dict — matches the CriticFinding model above."""
    return {
        "test": test,
        "threshold": threshold,
        "measured_value": round(float(measured_value), 4),
        "passed": bool(passed),
        "detail": detail,
    }


def check_leakage(df: pd.DataFrame, target_column: str) -> dict:
    """
    Leakage test: max absolute correlation between any single feature and
    the target. Only numeric features are checked directly; categorical
    features are label-encoded first so they aren't silently skipped.
    """
    work_df = df.copy()

    # Encode non-numeric columns so they're included in the correlation scan,
    # not silently dropped by .corr(). This matters — a leaking categorical
    # column should still be caught.
    for col in work_df.columns:
        if work_df[col].dtype == "object":
            work_df[col] = work_df[col].astype("category").cat.codes

    if target_column not in work_df.columns:
        return _finding("leakage", LEAKAGE_THRESHOLD, 0.0, True,
                         f"Target column '{target_column}' not found — skipped.")

    correlations = work_df.corr(numeric_only=True)[target_column].drop(target_column, errors="ignore")
    correlations = correlations.abs().dropna()

    if correlations.empty:
        return _finding("leakage", LEAKAGE_THRESHOLD, 0.0, True,
                         "No numeric/encodable features to check against target.")

    worst_col = correlations.idxmax()
    worst_val = correlations.max()
    passed = worst_val <= LEAKAGE_THRESHOLD

    detail = (
        f"Column '{worst_col}' correlates {worst_val:.4f} with target "
        f"'{target_column}' — {'exceeds' if not passed else 'below'} the "
        f"{LEAKAGE_THRESHOLD} ceiling."
    )
    return _finding("leakage", LEAKAGE_THRESHOLD, worst_val, passed, detail)


def check_contamination(df: pd.DataFrame) -> dict:
    """
    Contamination test: fraction of exact-duplicate rows (hash-based).
    Near-duplicate detection (fuzzy match) is a possible future upgrade —
    Day-0 spec starts with exact/near-dup via hashing; this implementation
    covers exact duplicates first since that's what the adversarial suite's
    duplication case actually produces.
    """
    n_total = len(df)
    if n_total == 0:
        return _finding("contamination", CONTAMINATION_THRESHOLD, 0.0, True,
                         "Empty dataset — nothing to check.")

    n_duplicate_rows = df.duplicated(keep="first").sum()
    fraction = n_duplicate_rows / n_total
    passed = fraction <= CONTAMINATION_THRESHOLD

    detail = (
        f"{n_duplicate_rows} of {n_total} rows ({fraction:.2%}) are exact "
        f"duplicates — {'exceeds' if not passed else 'below'} the "
        f"{CONTAMINATION_THRESHOLD:.0%} ceiling."
    )
    return _finding("contamination", CONTAMINATION_THRESHOLD, fraction, passed, detail)


def check_imbalance(df: pd.DataFrame, target_column: str) -> dict:
    """
    Imbalance test: minority-class recall using a quick baseline classifier
    (LogisticRegression on numeric-encoded features), NOT AutoGluon's own
    models — this is a fast, independent check, not a repeat of the
    Experiment Node's work.

    Binary classification only for now (matches the adversarial suite's
    Survived 0/1 target). Multiclass support is a possible follow-up.
    """
    if target_column not in df.columns:
        return _finding("imbalance", IMBALANCE_THRESHOLD, 1.0, True,
                         f"Target column '{target_column}' not found — skipped.")

    work_df = df.copy()
    y = work_df[target_column]
    X = work_df.drop(columns=[target_column])

    for col in X.columns:
        if X[col].dtype == "object":
            X[col] = X[col].astype("category").cat.codes
    X = X.fillna(X.median(numeric_only=True)).select_dtypes(include=[np.number])

    if y.nunique() != 2:
        return _finding("imbalance", IMBALANCE_THRESHOLD, 1.0, True,
                         f"Target has {y.nunique()} classes — imbalance check "
                         "currently only supports binary targets, skipped.")

    minority_class = y.value_counts().idxmin()

    try:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.3, random_state=42, stratify=y
        )
        clf = LogisticRegression(max_iter=1000)
        clf.fit(X_train, y_train)
        preds = clf.predict(X_test)

        true_positives = ((preds == minority_class) & (y_test == minority_class)).sum()
        actual_minority = (y_test == minority_class).sum()
        recall = true_positives / actual_minority if actual_minority > 0 else 0.0
    except Exception as e:
        return _finding("imbalance", IMBALANCE_THRESHOLD, 0.0, False,
                         f"Imbalance check failed to run ({e}) — treated as fail, "
                         "needs manual review.")

    passed = recall >= IMBALANCE_THRESHOLD
    overall_accuracy = (preds == y_test).mean()

    detail = (
        f"Minority class '{minority_class}' recall {recall:.2f} while overall "
        f"accuracy {overall_accuracy:.2f} — "
        f"{'below floor, headline metric masks failure' if not passed else 'above floor'}."
    )
    return _finding("imbalance", IMBALANCE_THRESHOLD, recall, passed, detail)


def critic_node(state: dict) -> dict:
    """
    LangGraph node entry point. Reads dataset_path + target_column from
    AgentState, runs all three checks, writes critic_findings back.

    Input (from AgentState): dataset_path, target_column, remediation
    Output (to AgentState):  critic_findings — list[dict], always exactly
                              3 entries (leakage, contamination, imbalance),
                              in that fixed order.

    Reads through _load_dataset(), the same call the Experiment Node makes, so
    both see an identical frame. That identity is load-bearing: on a retry lap
    the Critic must measure the repaired data the model was actually fit on,
    otherwise it would certify the raw upload and the leakage finding would
    still fire for a column that is no longer in the model's input.
    """
    df = _load_dataset(state)
    target_column = state["target_column"]

    findings = [
        check_leakage(df, target_column),
        check_contamination(df),
        check_imbalance(df, target_column),
    ]

    # critic_findings is current truth (LastValue — the Judge must see the data
    # as it is now). findings_history additionally appends, so the Reporter can
    # still show that leakage failed on lap 1 after lap 2 repairs it away.
    return {"critic_findings": findings, "findings_history": [findings]}


# ---------------------------------------------------------------------------
# Judge helpers — deterministic pieces the tool-calling Judge (app.agents.tools)
# reuses. The LLM-driven agent loop itself lives in app.agents.graph_agent; the
# old structured-output call_judge node has been removed.
# ---------------------------------------------------------------------------

def _rule_based_verdict(findings: list[CriticFinding]) -> str:
    """What the thresholds alone say — deterministic, no LLM."""
    return "reject" if any(not f.passed for f in findings) else "accept"


#IMPORTANT when critic rejects but judge accepts (edge case so need to flag for manual review)
def _apply_override_guardrail(decision: JudgeDecision, rule_verdict:str)-> JudgeDecision:
    """This function accounts the case if Judge says 'yes' (without justification) but rules_verdict says 'no'
    else if Judge gives Justification then flagged it out"""
    de_escalation= decision.verdict == 'accept' and rule_verdict == 'reject'
    if de_escalation and not decision.justification.strip():
        # no justification and de-escalation case
        decision.verdict= 'reject'
        decision.selected_model=None
        decision.overrode_rules=False
        decision.justification =("Override blocked: accept past a hard-fail with no "
                                  "justification. Reverted to rule-based reject.")
    elif de_escalation:
        decision.flagged_for_manual_review= True
    return decision


_VERDICT_LABEL = {"accept": "ACCEPT", "reject": "REJECT"}


def _fmt_score(value) -> str:
    """Leaderboard scores are floats, but never trust a dict you didn't build."""
    return f"{value:.4f}" if isinstance(value, (int, float)) else str(value)


def _fmt_repair(rem: dict) -> str:
    """One remediation directive as a short human phrase."""
    if rem.get("code"):
        one_line = " ".join(rem["code"].split())
        return f"ran `{one_line[:100]}{'…' if len(one_line) > 100 else ''}`"
    parts = []
    if rem.get("drop_columns"):
        parts.append("dropped " + ", ".join(f"`{c}`" for c in rem["drop_columns"]))
    if rem.get("dedupe"):
        parts.append("de-duplicated rows")
    return "; ".join(parts) or "_(no-op)_"


def _lap_table(r: dict) -> list[str]:
    """The before/after table — the single most important thing this run produces.

    Only rendered when there WAS more than one lap. On a single-lap run it would
    just restate the Critic Findings table below, and an empty "what we caught"
    section on a clean dataset reads like a bug.

    Pairing rule: remediation_history[i] is the repair the Judge prescribed after
    lap i, which produced lap i+1. So a repair is only shown as applied if a lap
    i+1 actually exists — a run that stopped early can leave a trailing repair
    with no following lap, and claiming it was applied would be a lie.
    """
    laps = min(len(r["leaderboard_history"]), len(r["findings_history"]))
    if laps < 2:
        return []

    lines = [
        "## What This Caught",
        "",
        "| Lap | Data | Top model | score_val | Failing tests | Repair prescribed |",
        "|-----|------|-----------|-----------|---------------|-------------------|",
    ]
    for i in range(laps):
        board = r["leaderboard_history"][i]
        top = board[0] if board else {}
        fails = [f.get("test") for f in r["findings_history"][i]
                 if not f.get("passed", True)]
        repair = "–"
        if i < len(r["remediation_history"]):
            repair = _fmt_repair(r["remediation_history"][i])
            if i + 1 >= laps:          # prescribed, but the Router refused the lap
                repair += " _(refused — retry bound)_"
        lines.append(
            f"| {i + 1} | {'as uploaded' if i == 0 else 'repaired'} | "
            f"{top.get('model', '–')} | {_fmt_score(top.get('score_val'))} | "
            f"{', '.join(f'**{t}**' for t in fails) or '–'} | {repair} |"
        )
    lines.append("")

    # The delta is the headline. Guard the arithmetic — score_val is a dict value
    # we did not build, and a failed model can carry NaN.
    first = (r["leaderboard_history"][0] or [{}])[0].get("score_val")
    last = (r["leaderboard_history"][laps - 1] or [{}])[0].get("score_val")
    first_fails = [f.get("test") for f in r["findings_history"][0]
                   if not f.get("passed", True)]
    if (isinstance(first, (int, float)) and isinstance(last, (int, float))
            and first == first and last == last):      # NaN != NaN
        direction = "fell" if last < first else "rose"
        lines += [f"The headline validation score {direction} from **{first:.4f}** to "
                  f"**{last:.4f}** ({last - first:+.4f}) once the data was repaired"
                  + (f" — the original score was inflated by "
                     f"{', '.join(first_fails)}." if first_fails else "."), ""]

    # The measured evidence behind lap 1's failures. Without this the table names
    # the test but not the number, and judge_decision.cited_evidence — which held
    # it — was overwritten by the final lap's decision. This is the only surviving
    # copy of what the Critic actually saw in the raw upload.
    original_fails = [f for f in r["findings_history"][0] if not f.get("passed", True)]
    if original_fails:
        lines += ["Measured on the data as uploaded:", ""]
        lines += [f"- **{f.get('test')}** — {f.get('detail')}" for f in original_fails]
        lines += [""]
    return lines


def _render_markdown(r: dict) -> str:
    """Render the report dict as markdown. Pure string work, no state reads."""
    # A no-verdict run is a real outcome here (see reporter_node), so name it
    # rather than rendering a bare 'NONE' that reads like a rendering bug.
    label = (_VERDICT_LABEL.get(r["verdict"], str(r["verdict"]).upper())
             if r["verdict"] else "NO VERDICT")
    selected = f" — `{r['selected_model']}`" if r["selected_model"] else ""

    lines = [
        "# ML Pipeline Audit Report",
        "",
        f"**Verdict:** {label}{selected}",
        f"**Run status:** `{r['status']}`",
        "",
    ]

    # Banners go above the fold — these are the whole reason this report exists.
    if r["flagged_for_manual_review"]:
        lines += ["> **FLAGGED FOR MANUAL REVIEW** — a human must sign this off "
                  "before anything ships.", ""]
    if r["overrode_rules"]:
        lines += [f"> **The Judge overrode the rules.** Thresholds alone said "
                  f"`{r['rule_based_verdict']}`; the Judge returned "
                  f"`{r['verdict']}`. The justification below is mandatory "
                  "reading, and this run belongs in overrides.md.", ""]
    if r["status"] == "exhausted":
        # The Judge ended without calling accept_model or reject_run — it declined
        # to act, or spent its refit budget and never decided. Nothing was promoted
        # and there is no justification to read, so say that outright: a silent
        # report with an empty verdict reads as a rendering bug, not a failed run.
        lines += ["> **Degraded run — no verdict.** The Judge finished without "
                  "calling accept_model or reject_run, so NOTHING was promoted. "
                  "The critic findings below are the last measured state; any "
                  "repairs the agent applied are listed under Repairs Applied.", ""]

    # Above the Justification: on a repaired run this is the only place the
    # original defect still exists, and it is the reason the run mattered.
    lines += _lap_table(r)

    lines += ["## Justification", "", r["justification"] or "_(none given)_", ""]

    lines += ["## Cited Evidence", ""]
    lines += ([f"- {e}" for e in r["cited_evidence"]]
              or ["_(none cited)_"])
    lines += [""]

    # What the agent actually DID, as opposed to what it concluded. On a clean
    # run this is empty and the section says so — an absent section would read
    # as "we forgot to log it" rather than "no repair was needed".
    lines += ["## Repairs Applied", ""]
    if r["remediation_history"]:
        lines += [f"The findings above were measured *after* these "
                  f"{len(r['remediation_history'])} repair(s), applied in order:", ""]
        for i, rem in enumerate(r["remediation_history"], start=1):
            if rem.get("code"):
                # A REPL cleaning step — show the actual code, it IS the evidence.
                lines.append(f"{i}. ran cleaning code:")
                lines.append("")
                lines.append("   ```python")
                lines += ["   " + cl for cl in rem["code"].splitlines()]
                lines.append("   ```")
                continue
            actions = []
            if rem.get("drop_columns"):
                actions.append("dropped " + ", ".join(f"`{c}`" for c in rem["drop_columns"]))
            if rem.get("dedupe"):
                actions.append("de-duplicated rows")
            lines.append(f"{i}. {'; '.join(actions) or '_(no-op)_'}")
    else:
        lines += ["_(none — the data was evaluated exactly as uploaded)_"]
    lines += [""]

    lines += ["## Critic Findings", ""]
    if r["critic_findings"]:
        lines += ["| Test | Result | Measured | Threshold |",
                  "|------|--------|----------|-----------|"]
        for f in r["critic_findings"]:
            mark = "PASS" if f.get("passed") else "**FAIL**"
            lines.append(f"| {f.get('test')} | {mark} | "
                         f"{f.get('measured_value')} | {f.get('threshold')} |")
        lines += [""]
        for f in r["critic_findings"]:
            if f.get("detail"):
                lines.append(f"- **{f.get('test')}** — {f['detail']}")
    else:
        lines += ["_(no findings — the Critic Node did not run)_"]
    lines += [""]

    lines += ["## Leaderboard (top 3)", ""]
    if r["leaderboard_top"]:
        lines += ["| Rank | Model | score_val |", "|------|-------|-----------|"]
        for i, row in enumerate(r["leaderboard_top"], start=1):
            lines.append(f"| {i} | {row.get('model')} | "
                         f"{_fmt_score(row.get('score_val'))} |")
    else:
        lines += ["_(no leaderboard — the Experiment Node did not run)_"]
    lines += [""]

    d = r["dataset"]
    lines += [
        "## Dataset",
        "",
        f"- target column: `{d['target_column']}`",
        f"- shape: {d['n_rows']} rows x {d['n_columns']} columns",
        f"- problem type: {d['problem_type']}",
        f"- AutoGluon fit time: {d['fit_time_seconds']}s",
    ]
    if d["halt_recommended"]:
        lines.append("- **halt_recommended: True** — the Data Node flagged this "
                     "dataset as unfit to train on.")
    lines += [""]

    return "\n".join(lines)


def reporter_node(state: AgentState) -> AgentState:
    """
    LangGraph node entry point — terminal (reporter -> END).

    Input (from AgentState):  judge_decision, critic_findings, leaderboard,
                              cleaned_data_summary, status
    Output (to AgentState):   report — the flattened decision record plus a
                              'markdown' key rendering the whole run.

    Every read is a .get() with a default. That is deliberate, not defensive
    padding: a run that fell over (status='exhausted', or a halt before the
    Experiment Node ever produced a leaderboard) is exactly when you most
    want a report, so this node must never be the thing that raises.
    """
    decision = state.get("judge_decision") or {}
    findings = state.get("critic_findings") or []
    leaderboard = state.get("leaderboard") or []
    summary = state.get("cleaned_data_summary") or {}

    # The only honest outcomes are the ones a terminal tool recorded: accept_model
    # and reject_run set both judge_decision and status themselves. Arriving here
    # any other way — the agent declined to call a tool, or burned its refit budget
    # without deciding — leaves NO verdict, and reporting that as a bare 'running'
    # would dress a failed run up as a normal one. Mark it exhausted so the
    # degraded banner fires. The router can't record this itself: a routing
    # function returns an edge label and any state it writes is discarded, so the
    # coercion lands here. Day-0 §10's "define the UI state for exhaustion".
    status = state.get("status")
    if not decision.get("verdict"):
        status = "exhausted"

    report = {
        "status": status,
        "run_id": state.get("run_id"),
        "verdict": decision.get("verdict"),
        "selected_model": decision.get("selected_model"),
        # Filled in by the /audit endpoint after the graph returns — exporting a
        # model is I/O against the artifact store, not a decision, and this node
        # must stay renderable from a hand-built state with no run scaffold.
        "model_artifact": None,
        "rule_based_verdict": decision.get("rule_based_verdict"),
        "overrode_rules": bool(decision.get("overrode_rules")),
        "flagged_for_manual_review": bool(decision.get("flagged_for_manual_review")),
        "justification": decision.get("justification", ""),
        "cited_evidence": decision.get("cited_evidence", []),
        "failing_tests": [f["test"] for f in findings if not f.get("passed", True)],
        "critic_findings": findings,
        "leaderboard_top": leaderboard[:3],
        "remediation_history": state.get("remediation_history") or [],
        "retry_count": state.get("retry_count", 0),
        "findings_history": state.get("findings_history") or [],
        "leaderboard_history": state.get("leaderboard_history") or [],
        "dataset": {
            "target_column": summary.get("target_column"),
            "n_rows": summary.get("n_rows"),
            "n_columns": summary.get("n_columns"),
            "problem_type": summary.get("problem_type"),
            "fit_time_seconds": summary.get("fit_time_seconds"),
            "halt_recommended": summary.get("halt_recommended"),
        },
    }
    report["markdown"] = _render_markdown(report)

    return {"report": report}


# ---------------------------------------------------------------------------
# Smoke tests — python -m app.agents.nodes [data|experiment|critic|judge|reporter|all]
#
# Note: 'experiment' actually fits models (60s time_limit per case), so it
# takes minutes where the others are near-instant.
# ---------------------------------------------------------------------------

def _smoke_data():
    from pathlib import Path

    DATA_DIR = Path(__file__).resolve().parents[3] / "data" / "adversarial_suite"

    test_cases = {
        "clean_1": ("titanic_clean_1.csv", "Survived"),
        "leakage": ("titanic_leakage.csv", "Survived"),
        "duplicates": ("titanic_duplicates.csv", "Survived"),
        "imbalance": ("titanic_imbalance.csv", "Survived"),
        "prompt_injection": ("titanic_prompt_injection.csv", "Survived"),
    }

    for name, (filename, target) in test_cases.items():
        path = DATA_DIR / filename
        if not path.exists():
            print(f"{name:18s} SKIPPED — file not found at {path}")
            continue
        result = data_node({"dataset_path": str(path), "target_column": target})
        s = result["cleaned_data_summary"]
        print(f"\n{name:18s} rows={s['n_rows']} cols={s['n_columns']} "
              f"halt_recommended={s['halt_recommended']}")
        if s["wrong_dtype_columns"]:
            print(f"  wrong_dtype_columns: {s['wrong_dtype_columns']}")
        if s["empty_columns"]:
            print(f"  empty_columns: {s['empty_columns']}")
        if s["single_class_target"]:
            print(f"  single_class_target: True")


def _smoke_experiment():
    from pathlib import Path

    DATA_DIR = Path(__file__).resolve().parents[3] / "data" / "adversarial_suite"

    test_cases = {
        "clean_1": ("titanic_clean_1.csv", "Survived"),
        "leakage": ("titanic_leakage.csv", "Survived"),
        "duplicates": ("titanic_duplicates.csv", "Survived"),
        "imbalance": ("titanic_imbalance.csv", "Survived"),
    }

    for name, (filename, target) in test_cases.items():
        path = DATA_DIR / filename
        if not path.exists():
            print(f"{name:12s} SKIPPED — file not found at {path}")
            continue
        result = experiment_node({"dataset_path": str(path), "target_column": target})
        top = result["leaderboard"][0]
        print(f"{name:12s} problem_type={result['cleaned_data_summary']['problem_type']:8s} "
              f"top_model={top['model']:20s} score_val={top['score_val']:.4f}")


def _smoke_critic():
    # Smoke test against the real adversarial suite built tonight.
    from pathlib import Path

    DATA_DIR = Path(__file__).resolve().parents[3] / "data" / "adversarial_suite"

    test_cases = {
        "clean_1": ("titanic_clean_1.csv", "Survived"),
        "leakage": ("titanic_leakage.csv", "Survived"),
        "duplicates": ("titanic_duplicates.csv", "Survived"),
        "imbalance": ("titanic_imbalance.csv", "Survived"),
    }

    for name, (filename, target) in test_cases.items():
        path = DATA_DIR / filename
        if not path.exists():
            print(f"{name:12s} SKIPPED — file not found at {path}")
            continue
        result = critic_node({"dataset_path": str(path), "target_column": target})
        fails = [f["test"] for f in result["critic_findings"] if not f["passed"]]
        print(f"\n{name:12s} failing_tests={fails or '-'}")
        for f in result["critic_findings"]:
            mark = "PASS" if f["passed"] else "FAIL"
            print(f"  [{mark}] {f['test']:15s} measured={f['measured_value']:<8} {f['detail']}")


def _smoke_reporter():
    """
    Renders the three states worth eyeballing. Uses the Day-8 mock findings
    plus hand-built judge_decisions — no Ollama, no AutoGluon, so this runs
    instantly and stays runnable when neither is up.
    """
    from app.mocks.critic_findings import MOCK_CASES

    clean, leaky = MOCK_CASES["titanic_clean"], MOCK_CASES["leakage"]

    scenarios = {
        # Ordinary accept — no banners should fire.
        "accept": (clean, "accepted", {
            "verdict": "accept", "selected_model": "WeightedEnsemble_L2",
            "justification": "All three critic tests pass; top model is a "
                             "reasonable margin above the rest.",
            "cited_evidence": [clean["critic_findings"][0]["detail"]],
            "rule_based_verdict": "accept", "overrode_rules": False,
            "flagged_for_manual_review": None,
        }),
        # De-escalation past a hard-fail — override + manual-review banners.
        "override_flagged": (leaky, "accepted", {
            "verdict": "accept", "selected_model": "CatBoost",
            "justification": "Accepting the #4 candidate: the top three are "
                             "inflated by the leaking column, CatBoost is not.",
            "cited_evidence": [leaky["critic_findings"][0]["detail"]],
            "rule_based_verdict": "reject", "overrode_rules": True,
            "flagged_for_manual_review": True,
        }),
        # The agent ended without calling a terminal tool — no judge_decision at
        # all. status must be coerced to 'exhausted' and the no-verdict banner
        # must fire; this is the run that used to render as a silent 'running'.
        "no_verdict": (leaky, "running", {}),
    }

    for name, (case, status, decision) in scenarios.items():
        state = {
            "status": status,
            "judge_decision": decision,
            "critic_findings": case["critic_findings"],
            "leaderboard": case["leaderboard"],
            "cleaned_data_summary": {
                "target_column": "Survived", "n_rows": 891, "n_columns": 12,
                "problem_type": "binary", "fit_time_seconds": 41.7,
                "halt_recommended": False,
            },
        }
        report = reporter_node(state)["report"]
        print(f"\n{'-' * 70}\nscenario: {name}  (failing_tests={report['failing_tests'] or '-'})\n{'-' * 70}")
        print(report["markdown"])

    # Partial state — a run that died before Experiment/Critic ever ran.
    # The Reporter must still produce a report rather than raise.
    empty = reporter_node({"status": "exhausted"})["report"]
    print(f"\n{'-' * 70}\nscenario: empty_state (must not raise)\n{'-' * 70}")
    print(empty["markdown"])


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252, which can't print ✅/❌

    SMOKE_TESTS = {
        "data": _smoke_data,
        "experiment": _smoke_experiment,
        "critic": _smoke_critic,
        "reporter": _smoke_reporter,
    }
    which = sys.argv[1] if len(sys.argv) > 1 else "all"

    if which == "all":
        to_run = SMOKE_TESTS.items()
    elif which in SMOKE_TESTS:
        to_run = [(which, SMOKE_TESTS[which])]
    else:
        sys.exit(f"Unknown smoke test '{which}'. Pick one of: "
                 f"{', '.join(SMOKE_TESTS)}, all")

    for name, smoke_test in to_run:
        print(f"\n{'=' * 30} {name} {'=' * 30}")
        smoke_test()
